### ISSUE TITLE
Background could be better...

### ISSUE THREAD

**Issue by shivan** [liulex/CopyAsHtml#1]
It only sets the background color, not a complete background. Tried on Windows 10.

See my examples:

![image](https://user-images.githubusercontent.com/1827692/27904255-60bcc5c2-623c-11e7-8273-1dc2bd879eeb.png)

See also this attachment for clipboard raw data:
[Detaildata.txt](https://github.com/liulex/CopyAsHtml/files/1127323/Detaildata.txt)

**Comment by liulex** [comment]
Where did you paste the data?

**Comment by shivan** [comment]
Pasted it into word or eMclient.

**Comment by liulex** [comment]
Thanks for the info. I will try to fix it when I have time.

**Comment by liulex** [comment]
Fixed with v2.0.0.
